# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'iOSTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'KalturaPlayer/Offline', :path => '..'
  pod 'KalturaPlayer/Offline_OTT', :path => '..'
  pod 'KalturaPlayer/Offline_OVP', :path => '..'

  target 'iOSTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
