source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0' # (define required version)

# Uncomment to use a local copy of PlayKit
KALTURA_PLAYER_LOCAL='../'

KALTURA_PLAYER_GIT='https://github.com/kaltura/kaltura-player-ios.git'
KALTURA_PLAYER_BRANCH=ENV['PK_BRANCH'] || ‘develop’

target 'KalturaPlayerExample' do
    
    pod 'PlayKitKava', :path => '../../playkit-ios-kava'
    pod 'PlayKitOTT', :path => '../../playkit-ios-ott'
    pod 'PlayKit', :path => '../../playkit-ios'
    
    if defined? KALTURA_PLAYER_LOCAL 
        pod 'KalturaPlayer/OVP', :path => KALTURA_PLAYER_LOCAL
        pod 'KalturaPlayer/OTT', :path => KALTURA_PLAYER_LOCAL
        pod 'KalturaPlayer/UI', :path => KALTURA_PLAYER_LOCAL
    else
        pod 'KalturaPlayer', :git => KALTURA_PLAYER_GIT, :branch => KALTURA_PLAYER_BRANCH
    end
end

pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end

post_install do |installer| 
    installer.pods_project.targets.each do |target| 
        target.build_configurations.each do |config| 
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
 	    if target.name == 'PlayKit'
	           config.build_settings['SWIFT_VERSION'] = '4.0'
	    end
        end 
    end 
end
