# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'tvOSTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'KalturaPlayer', :path => '..'
  pod 'KalturaPlayer/OTT', :path => '..'
  pod 'KalturaPlayer/OVP', :path => '..'

end
